In [4]:
import duckdb
import pandas as pd

In [2]:
sql_query = '''
show tables
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

                      name
0              first_model
1  parking_violation_codes
2  parking_violations_2023

In [3]:
sql_query_import_1 = '''
CREATE OR REPLACE TABLE parking_violation_codes AS
SELECT * 
FROM read_csv_auto(
    'data/dof_parking_violation_codes.csv',
    normalize_names=True)'''

sql_query_import_2 = '''
CREATE OR REPLACE TABLE parking_violations_2023 AS
SELECT *
FROM read_csv_auto(
    'data/parking_violations_issued_fiscal_year_2023_sample.csv',
    normalize_names=True)'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    con.sql(sql_query_import_1)
    con.sql(sql_query_import_2)

In [4]:
sql_query = '''
show tables
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

                      name
0              first_model
1  parking_violation_codes
2  parking_violations_2023

In [5]:
sql_query = '''
SELECT * FROM parking_violation_codes LIMIT 5
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

,code,definition,manhattan_96th_st_below,all_other_areas
0,1,FAILURE TO DISPLAY BUS PERMIT,515,515
1,2,NO OPERATOR NAM/ADD/PH DISPLAY,515,515
2,3,UNAUTHORIZED PASSENGER PICK-UP,515,515
3,4,BUS PARKING IN LOWER MANHATTAN,115,115
4,5,BUS LANE VIOLATION,250,250

In [6]:
sql_query = '''
SELECT * FROM parking_violations_2023 LIMIT 5
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

,summons_number,registration_state,plate_type,issue_date,violation_code,vehicle_body_type,vehicle_make,issuing_agency,vehicle_expiration_date,violation_location,...,from_hours_in_effect,to_hours_in_effect,vehicle_color,unregistered_vehicle,vehicle_year,meter_number,feet_from_curb,no_standing_or_stopping_violation,hydrant_violation,double_parking_violation
0,9010912681,CA,PAS,2022-10-11,17,SUBN,FORD,T,20220788,50,...,0700A,0400P,BLACK,<NA>,0,None,0,None,None,None
1,4858762841,NY,PAS,2023-08-21,36,4DSD,HONDA,V,0,<NA>,...,NaN,NaN,GY,<NA>,2003,None,0,None,None,None
2,4854645684,FL,PAS,2023-07-26,36,UT,BMW,V,0,<NA>,...,NaN,NaN,WHI,<NA>,2022,None,0,None,None,None
3,9044582707,NY,PAS,2023-04-10,21,SUBN,SUBAR,T,20231217,79,...,0900A,1030A,GY,<NA>,2017,None,0,None,None,None
4,9041503330,NY,PAS,2023-03-21,21,4DSD,CHEVR,T,20250320,26,...,1100A,1230A,BK,<NA>,2018,None,0,None,None,None

In [6]:
sql_query = '''
show tables
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

                      name
0              first_model
1  parking_violation_codes
2  parking_violations_2023

In [3]:
sql_query = '''
SELECT * FROM ref_model
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

   count_star()
0            97

In [8]:
sql_query = '''
select * from bronze_parking_violations limit 3
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

,summons_number,registration_state,plate_type,issue_date,violation_code,vehicle_body_type,vehicle_make,issuing_agency,vehicle_expiration_date,violation_location,violation_precinct,issuer_precinct,issuer_code,issuer_command,issuer_squad,violation_time,violation_county,violation_legal_code,vehicle_color,vehicle_year
0,9010912681,CA,PAS,2022-10-11,17,SUBN,FORD,T,20220788,50,50,50,365910,T201,D,0825A,BX,<NA>,BLACK,0
1,4858762841,NY,PAS,2023-08-21,36,4DSD,HONDA,V,0,<NA>,0,0,0,NaN,NaN,1036A,BK,True,GY,2003
2,4854645684,FL,PAS,2023-07-26,36,UT,BMW,V,0,<NA>,0,0,0,NaN,NaN,0126P,QN,True,WHI,2022

In [13]:
sql_query = '''
SELECT * FROM silver_parking_violation_codes LIMIT 3
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

,violation_code,definition,is_manhattan_96th_st_below,fee_usd
0,1,FAILURE TO DISPLAY BUS PERMIT,True,515
1,1,FAILURE TO DISPLAY BUS PERMIT,False,515
2,2,NO OPERATOR NAM/ADD/PH DISPLAY,True,515

In [15]:
sql_query = '''
SELECT * FROM silver_violation_tickets limit 3
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

,summons_number,issue_date,violation_code,is_manhattan_96th_st_below,issuing_agency,violation_location,violation_precinct,issuer_precinct,issuer_code,issuer_command,issuer_squad,violation_time,violation_county,violation_legal_code,fee_usd
0,9010912681,2022-10-11,17,False,T,50,50,50,365910,T201,D,0825A,BX,<NA>,95
1,4858762841,2023-08-21,36,False,V,<NA>,0,0,0,NaN,NaN,1036A,BK,True,50
2,4854645684,2023-07-26,36,False,V,<NA>,0,0,0,NaN,NaN,0126P,QN,True,50

In [18]:
sql_query = '''
select * from gold_vehicles_metrics limit 3
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

  registration_state  ticket_count
0                 NJ          9258
1                 PA          3514
2                 FL          2414

In [3]:
sql_query = '''
select * from "nyc_parking_violations"."main_dbt_test__audit"."violation_codes_revenue"
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

   violation_code  total_revenue_usd
0              41                0.0

In [5]:
sql_query_import_1 = '''
CREATE OR REPLACE TABLE parking_violation_codes AS
SELECT * 
FROM read_csv_auto(
    'data/dof_parking_violation_codes.csv',
    normalize_names=True)'''

sql_query_import_2 = '''
CREATE OR REPLACE TABLE parking_violations_2023 AS
SELECT *
FROM read_csv_auto(
    'data/parking_violations_issued_fiscal_year_2023_sample.csv',
    normalize_names=True)'''

with duckdb.connect('data/prod_nyc_parking_violations.db') as con:
    con.sql(sql_query_import_1)
    con.sql(sql_query_import_2)

In [6]:
sql_query = '''
show tables
'''

with duckdb.connect('data/prod_nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

                             name
0  bronze_parking_violation_codes
1       bronze_parking_violations
2             gold_ticket_metrics
3           gold_vehicles_metrics
4         parking_violation_codes
5         parking_violations_2023
6        silver_violation_tickets
7       silver_violation_vehicles